[package]
name = "jbot"
version = "0.1.0"
authors = ["HBcao <hbcaoqaq@outlook.com>"]
license = "MIT OR Apache-2.0"
description = ""
homepage = "https://github.com/HBcao233/jbot"
repository = "https://github.com/HBcao233/jbot"
keywords = ["telegram", "bot"]
categories = []
edition = "2024"

[features]
core_curl = [
    "dep:wreq",
    "dep:wreq-util",
    "dep:futures-util",
]

roll = ["dep:rand"]
merge = []
group_config = []
verify = ["group_config", "dep:rand"]

bili = [
    "core_curl",
    "dep:regex",
    "dep:jb-core",
]
douyin = [
    "core_curl",
    "dep:regex",
    "dep:thiserror",
    "dep:serde",
    "dep:serde_json",
    "dep:form_urlencoded",
    "dep:md5",
    "dep:rand",
    "dep:sm3",
]
twitter = [
    "core_curl",
    "dep:regex",
    "dep:thiserror",
    "dep:serde",
    "dep:serde_json",
]

[dependencies]
jbot-macro = { path = "../jbot-macro" }
jb-core = { path = "../jb-core", optional = true }

grammers-client = { path = "../../grammers/grammers-client", default-features = false, features = ["fs", "html"] }
grammers-session = { path = "../../grammers/grammers-session", default-features = false, features = ["sqlite-storage"] }
grammers-tl-types = { path = "../../grammers/grammers-tl-types" }

anyhow = { version = "1.0", default-features = false }
dotenvy = { version = "0.15", default-features = false }
linkme = { version = "0.3", default-features = false }
libsql = { version = "0.9", default-features = false, features = ["core"] }
tokio = { version = "1.52.3", default-features = false, features = [
    "signal", "process"
] }
jiff = { version = "0.2.37", default-features = false, features = ["std"] }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = ["ansi", "fmt", "std", "env-filter"]}
tracing-appender = { version = "0.2", default-features = false }
sysinfo = { version = "0.39", default-features = false, features = ["disk", "system"] }

regex = { version = "1.13", optional = true }
wreq = { workspace = true, optional = true }
wreq-util = { workspace = true, optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
thiserror = { version = "2.0", optional = true }
futures-util = { version = "0.3", optional = true }
rand = { version = "0.10", optional = true }
form_urlencoded = { version = "1.2", optional = true }
md5 = { version = "0.8", optional = true }
sm3 = { version = "0.5", optional = true }
